plugins {
    id 'blib-multiloader-root'
}

allprojects {
    repositories {
        mavenLocal()
    }

    configurations.configureEach {
        resolutionStrategy.eachDependency { details ->
            if (details.requested.group == 'com.blib' && details.requested.name.startsWith('blib-')) {
                details.useVersion rootProject.blib_version
                details.because 'Some published AVP/BLib POMs point at missing BLib versions.'
            }
        }
    }
}

blib {
    version = project.blib_version
    recipeViewer = 'rei'

    mod {
        author = 'Stargazer Studios'
        credits = 'Stargazer Studios'
        description = 'A module for the AVP universe that adds human content.'
        group = 'com.avp.human'
        icon = 'assets/avp_human/icon.png'
        id = 'avp_human'
        license = 'All Rights Reserved'
        name = 'AVP (Human)'
        version = '0.1.7'

        publish {
            dryRun = true

            discordWebhook {
                username = "MU/TH/UR"
                avatarUrl = "https://i.imgur.com/5Y0EZ9x.jpeg"
                thumbnailUrl = "https://cdn.modrinth.com/data/Uqo0H9FX/8ffabe2f364c34e6b0f13019664c5fe4989c2f95_96.webp"
            }

            curseforge {
                projectId = '1406348'
                projectSlug = 'avp-human'
            }

            modrinth {
                projectId = 't2hZvxHn'
            }
        }
    }

    maven {
        repository 'https://maven.bvanseghi.dev/avp_alien'
        repository 'https://maven.bvanseghi.dev/avp_predator'
        repository 'https://maven.bvanseghi.dev/blib_engine'

        publish {
            url = 'https://maven.bvanseghi.dev/avp_human/'

            credentials {
                usernameEnv = 'AVP_MAVEN_USERNAME'
                passwordEnv = 'AVP_MAVEN_PASSWORD'
            }
        }
    }
}
